spring.application.name=microservice-ia
spring.datasource.url=jdbc:postgresql://localhost:5432/telecom
spring.datasource.username=khaled
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=klodezdinfaute@gmail.com
spring.mail.password=dcch nide bxsh ibos
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Cache automatique
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=30s,refreshAfterWrite=25s

# Thread pool automatique
spring.task.execution.pool.core-size=20
spring.task.execution.pool.max-size=50
spring.task.execution.pool.queue-capacity=200

# Timeout automatique
ia.python.timeout.seconds=2

# Refresh automatique
ia.cache.refresh.interval=30000
ia.cache.warmup.enabled=true
# Server
server.port=8085
